sudo: required
services:
  - docker

before_install:
  - docker build -t jollynjose/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jollynjose/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-practice'
  env: 'Dockerpractice-env'
  bucket_name: 'elasticbeanstalk-us-east-2-218754881418'
  bucket_path: 'docker-practice'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
